/* Author: Sanchita Kanade
   Class: Advanced Object-Oriented Design & Programming (Fall 2019)
   File:EquationViewGUI.java
 */
package spreadsheet;

import designpattern.memento.Memento;
import designpattern.memento.Originator;
import designpattern.memento.RestorePreviousState;
import designpattern.memento.TextFieldGUI;
import designpattern.observer.*;

import javax.swing.*;
import java.util.Stack;

public class EquationViewGUI extends JFrame implements TextFieldGUI {
    private ValueViewGUI valView;
    private Stack<Memento> history; //stack to store undo history of Equation View
    private Originator equationView;

    private JButton jButton1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField6;
    private JTextField jTextField7;
    private JTextField jTextField8;
    private JTextField jTextField9;

    public EquationViewGUI() {
        history = new Stack<>();
        equationView = new Originator(history);
        initComponents();
    }

    public EquationViewGUI(ValueViewGUI valView) {
        history = new Stack<>();
        equationView = new Originator(history);
        this.valView = valView; //changed
        initComponents();
    }

    public JButton getjButton1() {
        return jButton1;
    }

    private void initComponents() {
        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JLabel jLabel4 = new JLabel();
        JLabel jLabel5 = new JLabel();
        JLabel jLabel6 = new JLabel();
        JLabel jLabel7 = new JLabel();
        JLabel jLabel8 = new JLabel();
        JLabel jLabel9 = new JLabel();
        JLabel jLabel10 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jTextField4 = new JTextField();
        jTextField5 = new JTextField();
        jTextField6 = new JTextField();
        jTextField7 = new JTextField();
        jTextField8 = new JTextField();
        jTextField9 = new JTextField();
        jButton1 = new JButton();


        /*
         * Following code makes the designpattern.observer.TextFieldListenerA to designpattern.observer.TextFieldListenerI objects
         * observers of jTextFields in equation view GUI
         */
        jTextField1.addActionListener(new TextFieldListenerB(this));
        jTextField2.addActionListener(new TextFieldListenerA(this));
        jTextField3.addActionListener(new TextFieldListenerD(this));
        jTextField4.addActionListener(new TextFieldListenerC(this));
        jTextField5.addActionListener(new TextFieldListenerE(this));
        jTextField6.addActionListener(new TextFieldListenerF(this));
        jTextField7.addActionListener(new TextFieldListenerG(this));
        jTextField8.addActionListener(new TextFieldListenerI(this));
        jTextField9.addActionListener(new TextFieldListenerH(this));
        jButton1.addActionListener(new RestorePreviousState(this));

        // Following code in this method is autogenerated by NetBeans IDE while creating a EquationView GUI
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("spreadsheet.EquationViewGUI");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Equation View");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("$A");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("$B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("$C");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("$D");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("$H");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("$F");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("$E");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("$G");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("$I");

        jButton1.setText("Undo");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(jPanel1Layout.createParallelGroup
                                                        (GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE,
                                                                137, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE,
                                                                136, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                        GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField6, GroupLayout.
                                                                                PREFERRED_SIZE, 136,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField7,
                                                                        GroupLayout.PREFERRED_SIZE,
                                                                        137, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.
                                                                                ComponentPlacement.RELATED,
                                                                        29, Short.MAX_VALUE)
                                                                .addComponent(jTextField9,
                                                                        GroupLayout.PREFERRED_SIZE, 137,
                                                                        GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(145, 145, 145)
                                                                .addComponent(jButton1,
                                                                        GroupLayout.PREFERRED_SIZE, 136,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(213, 213, 213)
                                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE,
                                                        136, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE,
                                                        136, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE,
                                                        136, GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING,
                                        false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(278, 278, 278)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jLabel2)
                                                .addGap(133, 133, 133)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(85, 85, 85))
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel8)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel7)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel9)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(81, 81, 81))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel10)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE,
                                                136, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(504, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 25,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 66,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 63,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(342, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(null);
    }


    /*
     * following method is getting integer values from cells of value-view GUI
     * using cell-labels used in expression
     */
    public String getInputString(String[] expression) {
        return valView.getInputString(expression);
    }

    //this method creates designpattern.memento.Memento object to store state of the spreadsheet.EquationViewGUI
    public void createMemento() {
        equationView.createMemento(this);
    }

    //this method restores previous state of the spreadsheet.EquationViewGUI object.
    public void restoreState() {
        equationView.restoreState(this);
    }

    public ValueViewGUI getValView() {
        return valView;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public JTextField getjTextField9() {
        return jTextField9;
    }

}

