/* Author: Sanchita Kanade
   Class: Advanced Object-Oriented Design & Programming (Fall 2019)
   File:ValueViewGUI.java
 */

package spreadsheet;

import designpattern.memento.Memento;
import designpattern.memento.Originator;
import designpattern.memento.RestorePreviousState;
import designpattern.memento.TextFieldGUI;
import designpattern.observer.*;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.Stack;

public class ValueViewGUI extends JFrame implements TextFieldGUI {
    private Stack<Memento> history; //stack to store undo history of Value View
    private Originator valueViewOriginator;

    public ValueViewGUI() {
        history = new Stack<>();
        valueViewOriginator = new Originator(history);
        initComponents();
        getjTextField1().setText("0");
        getjTextField2().setText("0");
        getjTextField3().setText("0");
        getjTextField4().setText("0");
        getjTextField5().setText("0");
        getjTextField6().setText("0");
        getjTextField7().setText("0");
        getjTextField8().setText("0");
        getjTextField9().setText("0");
    }

    private void initComponents() {
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jTextField4 = new JTextField();
        jTextField5 = new JTextField();
        jTextField6 = new JTextField();
        jTextField7 = new JTextField();
        jTextField8 = new JTextField();
        jTextField9 = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jButton1 = new JButton();

        //this line makes the designpattern.memento.RestorePreviousState object observer or listener of the button "Undo"
        jButton1.addActionListener(new RestorePreviousState(this));

        // Following code in this method is autogenerated by NetBeans IDE while creating a ValueView GUI
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpreadSheetGUI");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("$A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("$B");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("$D");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("$C");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("$E");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("$F");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("$G");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("$H");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("$I");

        jLabel10.setBackground(new java.awt.Color(255, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Value View");

        jButton1.setText("Undo");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(348, 348, 348)
                                                .addComponent(jLabel8)
                                                .addGap(148, 148, 148)
                                                .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(198, 198, 198)
                                                .addComponent(jLabel1)
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel2)
                                                .addGap(132, 132, 132)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(300, 300, 300)
                                                .addComponent(jLabel10)))
                                .addContainerGap(180, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(160, 160, 160)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                        GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE,
                                                                97, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE))
                                                .addGap(55, 55, 55))
                                        .addGroup(GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addGap(186, 186, 186)
                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel7))
                                                        .addGap(102, 102, 102)))
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING,
                                        false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE,
                                                        102, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE,
                                                        102, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(62, 62, 62)
                                                        .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE,
                                                                102, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addGap(39, 39, 39)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 81,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 51,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 55,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 55,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 55,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE,
                                                        55, GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                        GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                        GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE,
                                                                55, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE,
                                                                55, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE,
                                                                55, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE,
                                                                60, GroupLayout.PREFERRED_SIZE))
                                                .addGap(37, 37, 37))
                                        .addGroup(GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel5)
                                                                .addComponent(jLabel6))
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE,
                                                                        55, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE,
                                                                        55, GroupLayout.PREFERRED_SIZE))
                                                        .addGap(169, 169, 169))))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pack();
        setLocationRelativeTo(null);
    }

    public JButton getjButton1() {
        return jButton1;
    }

    //this method creates designpattern.memento.Memento object to store the state of the spreadsheet.ValueViewGUI
    public void createMemento() {
        valueViewOriginator.createMemento(this);
    }

    //this method restores previous state of the spreadsheet.ValueViewGUI object.
    public void restoreState() {
        valueViewOriginator.restoreState(this);
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public JTextField getjTextField9() {
        return jTextField9;
    }

    //This method dynamically registers observers with jTextFields in value view, according to expression entered by user
    public void registerObserver(ActionListener observer, String[] expression) {
        for (int index = 0; index < expression.length; index++) {
            switch (expression[index]) {
                case "$A":
                    jTextField1.addActionListener(observer);
                    break;
                case "$B":
                    jTextField2.addActionListener(observer);
                    break;
                case "$C":
                    jTextField3.addActionListener(observer);
                    break;
                case "$D":
                    jTextField4.addActionListener(observer);
                    break;
                case "$E":
                    jTextField5.addActionListener(observer);
                    break;
                case "$F":
                    jTextField7.addActionListener(observer);
                    break;
                case "$G":
                    jTextField6.addActionListener(observer);

                    break;
                case "$H":
                    jTextField9.addActionListener(observer);
                    break;
                case "$I":
                    jTextField8.addActionListener(observer);
                    break;
            }
        }
    }

    //This method unregisters observers from unwanted jTextFields
    public void removeObserver(ActionListener observer) {
        JTextField[] textFields = {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8};

        for (JTextField textField : textFields) {

            if (observer instanceof ValueViewObserverA && textField.equals(jTextField1)) {
            } else if (observer instanceof ValueViewObserverB && textField.equals(jTextField2)) {
            } else if (observer instanceof ValueViewObserverC && textField.equals(jTextField3)) {
            } else if (observer instanceof ValueViewObserverD && textField.equals(jTextField4)) {
            } else if (observer instanceof ValueViewObserverE && textField.equals(jTextField5)) {
            } else if (observer instanceof ValueViewObserverF && textField.equals(jTextField7)) {
            } else if (observer instanceof ValueViewObserverG && textField.equals(jTextField6)) {
            } else if (observer instanceof ValueViewObserverH && textField.equals(jTextField9)) {
            } else if (observer instanceof ValueViewObserverI && textField.equals(jTextField8)) {
            } else {
                textField.removeActionListener(observer);
            }
        }
    }

    //This method fetches actual values for variables in expression and forms input string for evaluating the expression
    public String getInputString(String[] expression) {
        for (int index = 0; index < expression.length; index++) {
            switch (expression[index]) {
                case "$A":
                    expression[index] = getjTextField1().getText();
                    break;
                case "$B":
                    expression[index] = getjTextField2().getText();
                    break;
                case "$C":
                    expression[index] = getjTextField3().getText();
                    break;
                case "$D":
                    expression[index] = getjTextField4().getText();
                    break;
                case "$E":
                    expression[index] = getjTextField5().getText();
                    break;
                case "$F":
                    expression[index] = getjTextField7().getText();
                    break;
                case "$G":
                    expression[index] = getjTextField6().getText();
                    break;
                case "$H":
                    expression[index] = getjTextField9().getText();
                    break;
                case "$I":
                    expression[index] = getjTextField8().getText();
                    break;
            }
        }
        return String.join(" ", expression);
    }

    // Variables declaration
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField6;
    private JTextField jTextField7;
    private JTextField jTextField8;
    private JTextField jTextField9;
    private JButton jButton1;
}
