/* Author: Sanchita Kanade
   Class: Advanced Object-Oriented Design & Programming (Fall 2019)
   File:ToggleViewsGUI.java
 */

import spreadsheet.EquationViewGUI;
import spreadsheet.ValueViewGUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ToggleViewsGUI extends javax.swing.JFrame implements ActionListener {
    private ValueViewGUI valueView;
    private EquationViewGUI equationView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton toggleViews;

    public ToggleViewsGUI() {
        valueView = new ValueViewGUI();
        equationView = new EquationViewGUI(valueView);
        initComponents();
    }

    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        toggleViews = new javax.swing.JToggleButton();

        //Following code makes the ToggleViewsGUI object listener of the button
        toggleViews.addActionListener(this);

        // Following code in this method is autogenerated by NetBeans IDE while creating a ToggleViewsGUI
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("toggleButtonGUI");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        toggleViews.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        toggleViews.setText("Value View");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(toggleViews, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(toggleViews, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }


    public EquationViewGUI getEquationView() {
        return equationView;
    }

    public ValueViewGUI getValueView() {
        return valueView;
    }

    //This method gets called when a user hits a Value View button
    @Override
    public void actionPerformed(ActionEvent e) {
        if (toggleViews.isSelected()) {
            toggleViews.setText("Equation View");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    equationView.setVisible(true);
                    valueView.setVisible(false);
                }
            });
        } else {
            toggleViews.setText("Value View");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    valueView.setVisible(true);
                    equationView.setVisible(false);
                }
            });
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToggleViewsGUI().setVisible(true);
            }
        });
    }
}


